### ISSUE TITLE
Multi-page layout

### ISSUE THREAD

**Issue by doxxx** [doxxx/ffxiv-craft-opt-web#58]
I've been working on a multi-page layout (in the multi-page-layout branch) for a while now. It's currently publicly available at http://ffxiv-beta.lokyst.net/ and should be mostly in sync with the master branch.

The intention with this new layout is to reduce the amount of stuff visible on the page to only what you need for a particular "mode" of use. So for example, once the crafter stats and available actions are set, it is unlikely that you will need to adjust them while working with the sequence and solver. Similarly, options don't need to be visible all the time either.

I also wanted to improve the appearance and usability of the site on touch devices and devices with small screens. Mainly, this meant no Bootstrap popup dialogs and reducing the complexity of the layout so that it could more gracefully degrade to fit smaller screens.

Under the hood, I've also tried to make the code more modular, particularly controllers.js.

#### TODO: 

- [x] Convert the Macro popup dialog into an inline form.
- [x] Figure out better solution for page switching when top bar switches to collapsed mode at smaller screen widths.
- [x] Split Simulator and Solver into separate pages.
- [x] Move Options page into modal dialog -- must degrade gracefully on smaller screens
- [x] Clicking "Solve..." button on Simulator page should switch to Solver page AND start the solver
- [x] Add Macro tab to log tabs on Solver page that shows the macro for the Solver result
- [x] Better layout of saved synths buttons and name.

**Comment by lokyst** [comment]
Options button is not visible once you scroll down to view the console log section.

**Comment by lokyst** [comment]
- [ ] Split Solve console log into probabilistic and montecarlo sim tabs.
